.TH deepsea 7
.SH NAME
DeepSea stage 1 \- a deeper insight
.SH DESCRIPTION
.B DeepSea Stage 1 (Discovery)
is a Salt orchestration that collects hardware information from Salt minions.
.RE
.PD
.SH PREFACE
.PP
This stage gathers various hardware details such as device names and network interfaces.  The results are stored in
.B /srv/pillar/ceph/proposals.
.PP
.B Validation
.RS
DeepSea verifies that the salt-api is running, deepsea_minions is set - see
.B deepsea-minions(7),
the master minion is present and Ceph packages are available.
.RE

.B Populate roles, Ceph configuration
.RS
Creates configuration files to allow the administrator to assign roles to minions and provides a fundamental Ceph configuration.  
.RE

.B Populate hardware profiles
.RS
DeepSea detects disks that are suitable for Ceph (i.e. no partitions) and creates a default profile based on the available HDD, SSD and NVME devices.  To learn about custom profiles, run

salt-run proposal.help
.RE

.SH EXAMPLE
salt-run state.orch ceph.stage.1
.PP
This command can also be used with the
.B deepsea(1)
to give feedback during the process from the Salt event bus. Salt orchestrations are unnervingly silent during execution and only report when complete.
.PP
deepsea salt-run state.orch ceph.stage.1
.PP
deepsea stage run ceph.stage.1

.SH AUTHOR
Joshua Schmid <jschmid@suse.com>
.SH SEE ALSO
.BR deepsea (1),
.BR deepsea (7),
.BR deepsea-commands (7),
.BR deepsea-stage-0 (7),
.BR deepsea-stage-2 (7),
.BR deepsea-stage-3 (7),
.BR deepsea-stage-4 (7),
.BR deepsea-stage-5 (7),
.BR deepsea-customization (7),
.BR deepsea-mines (7)
