.TH deepsea 7
.SH NAME
DeepSea stage 0 \- a deeper insight
.SH DESCRIPTION
.B DeepSea Stage 0 (Prep)
is a Salt orchestration that prepares Salt minions to run Ceph.  Tasks include maintenance updates.
.RE
.PD
.SH PREFACE
.PP
Stage 0 behaves differently depending on the presence of a Ceph cluster. 
On the first invocation of a fresh installation, DeepSea will run all operations in parallel. On subsequent invocations, Stage 0 will process minions serially.  The operation is divided into three sections.
.SS Master

.B Validation
.RS
DeepSea performs a set of system validation tests before running the remainder of the stage.  These tests check the deepsea_minions setting - see 
.B deepsea-minions(7),
the presence of a master minion and Ceph packages.
.RE

.B Salt-Api
.RS
Since openATTIC communicates with DeepSea via Salt, the salt-api service must be 
enabled and running for openATTIC to establish a connection with Salt.
.RE

.B Sync
.RS
Salt synchronizes (or updates) the master minion with the latest components such as modules.
.RE

.B Updates
.RS
The master minion will be patched.
.RE

.B Reboot
.RS
The master will reboot if necessary.  Adjust ceph.stage.prep.master to change the default behavior.  See
.B deepsea-customization(7).
.RE

.RE
.B Readycheck
.RS
Make sure all minions are up. Bails out after 300 seconds if all minions have not responded.
.RE

.SS Minions
.B Sync
.RS
Salt synchronizes (or updates) all minions with the latest components.
.RE

.B Mines
.RS
Mines are synced to the cluster. See deepsea-mines (7) for more information
.RE

.B Fresh Install
.RS
All minions will process the next steps in parallel to deploy a cluster as quickly as possible.
.RE

.RS
.B Update
.RS
Packages are updated.
.RE

.B Restart
.RS
Each minion will reboot if necessary.
.RE
.RE

.B Existing Cluster
.RS
All minions will process the next steps sequentially.
.RE

.RS
.B Health Check
.RS
DeepSea expects the Ceph cluster to be in a healthy state before continuing. Stage 0 will abort if the cluster does not reach a HEALTH_OK state within 5 minutes.
.RE

.B Running Processes
.RS
Every assigned role has related services.  These services have one or more running processes.  If all processes are not running, Stage 0 will abort.  The wait time is 15 minutes for a physical machine and 2 minutes for a virtual machine.
.RE

.B Update
.RS
Packages are updated.
.RE

.B Restart
.RS
Each minion will reboot if necessary.  To prevent unnecessary data rebalancing, DeepSea sets the 'noout' flag.  The flag is unset once the minion is online.
.RE

.RE
.SS Process Restart
.RS
Updated services may require a restart.  The restart orchestration will restart a process if a process is using a
.B deleted file
or the 
.B configuration has changed.
Each process is restarted sequentially with the same conditions as before.  Stage 0 will abort if processes do not restart successfully.
.RE

.SH EXAMPLE
salt-run state.orch ceph.stage.0
.PP
This command can also be used with the
.B DeepSea cli
to give feedback during the process from the Salt event bus. 
Salt orchestrations are unnervingly silent during execution and only report when complete.
.PP
deepsea salt-run state.orch ceph.stage.0
.PP
deepsea stage run ceph.stage.0

.SH AUTHOR
Joshua Schmid <jschmid@suse.com>
.SH SEE ALSO
.BR deepsea (1),
.BR deepsea (7),
.BR deepsea-commands (7),
.BR deepsea-stage-1 (7),
.BR deepsea-stage-2 (7),
.BR deepsea-stage-3 (7),
.BR deepsea-stage-4 (7),
.BR deepsea-stage-5 (7),
.BR deepsea-customization (7),
.BR deepsea-mines (7)
