.TH deepsea 7
.SH NAME
deepsea mines
.SH DESCRIPTION
.B Mines
are a salt concept to collect arbitrary data from the Minions and store it on the master. For more information read https://docs.saltstack.com/en/latest/topics/mine/

Deepsea uses mines to retrieve the information about the underlying hardware configuration and about rbd images.

.SH AUTHOR
Joshua Schmid <jschmid@suse.com>
.SH SEE ALSO
.BR deepsea (1),
.BR deepsea (7),
