.TH deepsea-stage 1 "DeepSea CLI man page"
.SH NAME
deepsea-stage - DeepSea stage related commands.

.SH SYNOPSIS
deepsea stage <command>

.SH DESCRIPTION
Commands for running and showing DeepSea stage steps

.SH COMMANDS
.B run
.RS
Runs a DeepSea stage and shows its execution progress. See
.BR deepsea-stage-run(1)


.RE
.B dry-run
.RS
Shows the execution steps of a DeepSea stage. See
.BR deepsea-stage-show(1)
