.TH deepsea 7
.SH NAME
DeepSea stage 5 \- a deeper insight
.SH DESCRIPTION
.B DeepSea Stage 5 (Removal)
is a Salt orchestration that removes roles.
.RE
.PD
.SH Preface
.PP
This stage removes configurations from the Ceph cluster and individual minions. The states related to removing Ceph configurations are in 
.B /srv/salt/ceph/remove
and those related to rescinding roles from minions are in
.B /srv/salt/ceph/rescind. 

.B Services
.RS
To remove a service from a minion, remove the role assignment from the policy.cfg, run Stage 2 - see
.B deepsea-stage-2(7) 
and then run Stage 5.
.RE

.SH EXAMPLE
salt-run state.orch ceph.stage.5
.PP
This command can also be used with the
.B deepsea(1)
to give feedback during the process from the Salt event bus.  Salt orchestrations are unnervingly silent during execution and only report when complete.
.PP
deepsea salt-run state.orch ceph.stage.5
.PP
deepsea stage run ceph.stage.5

.SH AUTHOR
Joshua Schmid <jschmid@suse.com>
.SH SEE ALSO
.BR deepsea (1),
.BR deepsea (7),
.BR deepsea-commands (7),
.BR deepsea-stage-0 (7),
.BR deepsea-stage-1 (7),
.BR deepsea-stage-2 (7),
.BR deepsea-stage-3 (7),
.BR deepsea-stage-4 (7),
.BR deepsea-customization (7),
.BR deepsea-mines (7)
