.TH deepsea 7
.SH NAME
DeepSea stage 4 \- a deeper insight
.SH DESCRIPTION
.B DeepSea Stage 4 (Services)
is a Salt orchestration that deploys the gateway services and graphical interface of Ceph.
.RE
.PD
.SH Preface
.PP
The services iSCSI, CephFS, RadosGW, Ganesha and openATTIC are available.

.B Validation
.RS
DeepSea check for incompatible openATTIC issues.
.RE

.B iSCSI
.RS
Configure and start igw (iSCSI GateWay) assigned minions.
.RE

.B CephFS
.RS
Configure and start mds.
.RE

.B RadosGW
.RS
Configure and start rgw.  DeepSea also supports custom RGW configurations.
.RE

.B Ganesha
.RS
Configure and start ganesha.  Ganesha provides NFS for RadosGW, CephFS or both.
.RE

.B openATTIC
.RS
Configure and start the openATTIC graphical standalone interface.
.RE

.RE
.SS Process Restart
.RS
Updated services may require a restart.  If a process is using a
.B deleted file
or the
.B configuration has changed,
then the orchestration will restart that process.  Each process is restarted sequentially with the same health checks as Stage 0.  Stage 4 will abort if processes do not restart successfully.  Only Stage 4 related services (igw, mds, rgw, ganesha, openattic) will be restarted.
.RE

.SH EXAMPLE
salt-run state.orch ceph.stage.4
.PP
This command can also be used with the
.B deepsea(1)
to give feedback during the process from the Salt event bus.  Salt orchestrations are unnervingly silent during 
execution and only report when complete.
.PP
deepsea salt-run state.orch ceph.stage.4
.PP
deepsea stage run ceph.stage.4

.SH AUTHOR
Joshua Schmid <jschmid@suse.com>
.SH SEE ALSO
.BR deepsea (1),
.BR deepsea (7),
.BR deepsea-commands (7),
.BR deepsea-stage-0 (7),
.BR deepsea-stage-1 (7),
.BR deepsea-stage-2 (7),
.BR deepsea-stage-3 (7),
.BR deepsea-stage-5 (7),
.BR deepsea-customization (7),
.BR deepsea-mines (7)
