#!/usr/bin/env bash

set -e

PIP=$(which pip2) # Use Python 2's pip by default
VENV_NAME='venv' # How original, I know
PYTHON_VERSION='/usr/bin/python2.7'

if ! $PIP show virtualenv &> /dev/null ; then
  echo "Could not find a suitable tool for creating Python venvs."
  exit 1
fi

echo "Creating venv in $(pwd)"
rm -rf venv
virtualenv --python=${PYTHON_VERSION} "${VENV_NAME}"
#  install venv requirements in a subshell in case of errors
( source $VENV_NAME/bin/activate
  pip install -r requirements.txt
)

cat << EOF

Venv creation and installation successful!

To activate the virtual environment again, execute:
> source $VENV_NAME/bin/activate

To deactivate the environment, simply execute:
> deactivate
EOF
